services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    environment:
      - APP_PORT=${APP_PORT:-8000}
    env_file:
      - path: .env
        required: false
